name: recipe_master
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter 
  flutter_localizations: 
    sdk: flutter
  flutter_svg: ^2.0.12
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  connectivity_plus: ^6.1.0
  gradient_borders: ^1.0.2
  image_picker: ^1.0.4
  permission_handler: ^11.1.0
  fl_chart: ^0.69.0
  share_plus: ^10.0.2
  get: ^4.6.6
  web: any
  universal_html: ^2.2.4
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true 
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoMedium.ttf
          weight: 500
        - asset: assets/fonts/RobotoBold.ttf
          weight: 700
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
    - family: Rozha One
      fonts: 
        - asset: assets/fonts/RozhaOneRegular.ttf
          weight: 400
